# Generated by Django 3.1.1 on 2020-09-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetail',
            name='Category',
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='expenditureAmount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
