# Generated by Django 3.1.1 on 2020-09-07 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0002_auto_20200906_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='ExpenseCategory',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='category',
            new_name='categoryName',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 7)),
        ),
        migrations.DeleteModel(
            name='ExpenseDetail',
        ),
    ]
