# Generated by Django 3.1.1 on 2020-09-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200907_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2020, 9, 10)),
        ),
    ]
