# Generated by Django 3.1.1 on 2020-09-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200910_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='dateAdded',
            new_name='date',
        ),
    ]
